spring:
  profiles:
    group:
      prod1: prod-db
      prod2: prod-db
    include:
      - token-secret
      - oauth2
  redis:
    host: 127.0.0.1
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:paws
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true