spring:
  config:
    activate:
      on-profile: local
ffmpeg:
  ffmpegPath: '${user.dir}\ffmpeg.exe'
  ffprobePath: '${user.dir}\ffprobe.exe'
  chunkUnit: 10
---
spring:
  config:
    activate:
      on-profile: prod1, prod2
ffmpeg:
  ffmpegPath: /home/ec2-user/app/ffmpeg.exe
  ffprobePath: /home/ec2-user/app/ffprobe.exe
  chunkUnit: 10