spring:
  config:
    activate:
      on-profile: local
ffmpeg:
  ffmpegPath: '${user.dir}\ffmpeg.exe'
  ffprobePath: '${user.dir}\ffprobe.exe'
  convert:
    path: '${user.dir}\convert\'
  chunkUnit: 10
---
spring:
  config:
    activate:
      on-profile: prod1, prod2
ffmpeg:
  ffmpegPath: /home/ec2-user/app/ffmpeg
  ffprobePath: /home/ec2-user/app/ffprobe
  convert:
    path: /home/ec2-user/convert
  chunkUnit: 10