spring:
  profiles:
    group:
      prod1: prod-db
      prod2: prod-db
    include:
      - token-secret
      - oauth2
      - aws
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 220MB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testdb
    username: test
    password: as824655
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    credentials:
      access-key: dummy-data
      secret-key: dummy-data
    region:
      static: ap-northeast-2
    s3:
      bucket: numble-video
    stack:
      auto: false
    image:
      s3:
        name: numble-image
      api-gateway:
        url: image-api-gateway-url
    video:
      s3:
        name: numble-video
      api-gateway:
        url: video-api-gateway-url

like:
  category:
    limit: 3
    rank:
      limit: 50
account:
  video:
    limit: 3
  detail:
    limit: 6